name: flutter_basic_structure
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build information
version: 1.0.0+2
environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons font for iOS style icons
  cupertino_icons: ^1.0.2
  # State management
  stacked: ^3.4.1
  # Navigation, snackbar, dialog box
  stacked_services: ^1.2.0
  # Compare objects
  equatable: ^2.0.5
  # Store small data in device cache
  shared_preferences: ^2.2.0
  # Native splash screen
  flutter_native_splash: ^2.3.1
  # Multi-language support
  easy_localization: ^3.0.2
  easy_localization_loader: ^1.0.0
  # API calls
  chopper: ^6.1.4
  http: ^0.13.5
  # Annotations for freezed code-generator
  freezed_annotation: ^2.2.0
  # JSON annotation
  json_annotation: ^4.5.0
  # Secure data storage
  flutter_secure_storage: ^8.0.0
  # Custom package for FCM services
  fcm_service:
    path: packages/fcm_service
  # SVG rendering and widget library
  flutter_svg: ^2.0.7
  # Manually set light or dark theme
  adaptive_theme: ^3.3.0
  dartz: ^0.10.1
  # JSON to Dart class generator
  json_to_type:
    path: packages/json_to_type

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generating files using Dart code
  build_runner: ^2.4.6
  # Code generator for Chopper package
  chopper_generator: ^6.0.3
  # Code generation for immutable classes
  freezed: ^2.3.5
  # Generate code for converting to/from JSON
  json_serializable: ^6.7.1
  # Stacked v1.9.0 generator
  stacked_generator: ^1.4.0
  # JsonToType generator
  json_to_type_generator:
    path: packages/json_to_type_generator
  web:
dependency_overrides:
  # Firebase Core platform interface
  firebase_core_platform_interface: 4.5.1
  # Recommended lints for good coding practices
  flutter_lints: ^2.0.0

# Flutter specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/translations/
    - assets/images/
    -
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/font/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/font/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/font/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/PlusJakartaSans-Bold.ttf
          weight: 700

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash_logo.png
  color_dark: "#ffffff"
  image_dark: assets/splash/splash_logo.png
  android_12:
    image: assets/splash/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash/splash_logo.png
    icon_background_color_dark: "#ffffff"
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center